- name: Toolbox container exists?
  containers.podman.podman_container_info:
    name: "{{ toolbox_container_name }}"
  register: toolbox_status

# - name: debug
#   debug:
#     msg: Create Toolbox!
#   when: toolbox_status.containers | length == 0 or toolbox_status.containers.0.Name != toolbox_container_name

- name: create toolbox
  ansible.builtin.shell: toolbox create -y
  when: toolbox_status.containers | length == 0 or toolbox_status.containers.0.Name != toolbox_container_name
  async: 3600
  poll: 15